Xavier learn more sect
EmpathyBytes/empathy-bytes-2024-2025 pull request #18
Opened 2024-11-10 04:11 UTC by xgenio3

Added the learn more section to the landing/home page and deleted the learn more button that was originally in the info card that's also in the landing page.

2024-11-12 21:07 UTC, AmaraWilliams requested changes
It looks great! Just some minor changes to the codebase before merging.

2024-11-12 21:07 UTC, AmaraWilliams commented on src/templates/article.js
I need you to revert the changes on this file since it's not relevant to the code your branch was working on. It just looks like it was tabbed over, but still.

2024-11-12 21:12 UTC, AmaraWilliams commented on src/components/learncard.js
The button links tot he **Project** and **Experiences** pages do not currently take you to the top of the page. You can look into the code for the logo located in the header and footer on how to do this. Right now, since the "LearnCard" is located at the bottom of the Homepage, it navigates to the bottom of the respective pages when clicked. This is what it looks like when I click on "Experiences" fromthe Learn Card. you can see the scrollbar is already scrolled down:
<img width="990" alt="image" src="https://github.com/user-attachments/assets/a16124e8-78b8-4563-b801-b10891cfbcbf">

2024-11-12 21:22 UTC, AmaraWilliams commented
Also, please add a before and after image to your pull request description.

2024-11-15 17:00 UTC, joshrsamuel commented
> Also, please add a before and after image to your pull request description.

Second this as well! It helps us get a sense of what changed visually without having to run the branch locally.

## Before
![Capture-2024-11-15-115415](https://github.com/user-attachments/assets/462b2565-118a-4107-a39f-b939723a8383)

## After
![Capture-2024-11-15-114908](https://github.com/user-attachments/assets/c501107b-7a78-415d-9b94-4cb570093d90)

2024-11-15 17:00 UTC, joshrsamuel requested changes

2024-11-15 17:10 UTC, joshrsamuel commented
> > Also, please add a before and after image to your pull request description.
> 
> Second this as well! It helps us get a sense of what changed visually without having to run the branch locally.
> 
> ## Before
> ![Capture-2024-11-15-115415](https://private-user-images.githubusercontent.com/83686250/386695139-462b2565-118a-4107-a39f-b939723a8383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2OTAzNDQsIm5iZiI6MTczMTY5MDA0NCwicGF0aCI6Ii84MzY4NjI1MC8zODY2OTUxMzktNDYyYjI1NjUtMTE4YS00MTA3LWEzOWYtYjkzOTcyM2E4MzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDE3MDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYmQxNzVkYzBkOWJhMDBiNTc2NmY0ZjljM2Q3ZjMzZDVhYjkyNTZhNjAyYTUxZGY4ZDQ5YjlmMTM3MzU4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._a4JehjisdPyxAybccotFQhAUmBJqRVgQpOT0nHbvs8)
> 
> ## After
> ![Capture-2024-11-15-114908](https://private-user-images.githubusercontent.com/83686250/386695205-c501107b-7a78-415d-9b94-4cb570093d90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2OTAzNDQsIm5iZiI6MTczMTY5MDA0NCwicGF0aCI6Ii84MzY4NjI1MC8zODY2OTUyMDUtYzUwMTEwN2ItN2E3OC00MTVkLTliOTQtNGNiNTcwMDkzZDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDE3MDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNTQ4Mjk5MTkwZmM0OTJhODZmMDdmOWY4MmI0YThhM2RjOWZjYmUyYzAxMGM5NDIzMjFlMzZlZjRmYjJmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w7CZOoL-_8s_FosXOGsL3MZGn7V-wS6qCnfGqnBfBqQ)

Another suggestion! Right now, your learn more section is centered, which doesn't really match the flow of the rest of the home page. You could play around with making the learn more section bigger so that it's width is the same as the space between the left side of the image and the right side of the "what is emapthy bytes" section.

2024-11-25 05:37 UTC, AmaraWilliams approved these changes
Thanks for fixing the scrolling issue! the comments are super helpful. I don't think @reach-router was known of!

2024-11-26 21:37 UTC, joshrsamuel approved these changes
Awesome changes! Like Amara said in her review, everything looks great. The scrolling change you made is also very interesting, I've never seen that before. If you had time, I'd love to hear more about how it works!

2024-11-27 16:58 UTC, merged