Favicon & Page Names!
EmpathyBytes/empathy-bytes-2024-2025 pull request #20
Opened 2024-11-12 21:43 UTC by joshrsamuel

# Problem
Our website currently only displays a favicon on some of our pages, and we only display a page name on the home page. This makes the website feel rough around the edges, and it also makes it harder for users with screen readers to navigate our site.

## Fix
Each page now has the EmpathyBytes logo as its favicon, and it's page name is the same as the title of the page. This should make the website feel more consistent as well as make it more accessible.

## Pictures
The pictures below display how the Experiences page on the website looked like in the browser tab UI, before and after this change.

### Before
![image](https://github.com/user-attachments/assets/0007df38-936d-47f6-b6e5-245d11f15826)

### After
![image](https://github.com/user-attachments/assets/a1a2ea0d-463b-4e30-85a7-029599994899)

## Minor Accessibility Improvement:
* Added `alt` attribute to the image in `src/pages/webteam.js` to improve accessibility.
* More images will receive alt attributes as I work on code cleanup, this is just one of the ones I caught while working on this ticket.

2024-11-13 19:52 UTC, AmaraWilliams requested changes
Nice work! It's a quick fix I think for the page title

2024-11-13 19:52 UTC, AmaraWilliams commented on src/pages/webteam.js
I think you should structure the header and alt file for webteam.js the same why you did for the other files. I noticed your changes had no effect for this specific page.
![image](https://github.com/user-attachments/assets/7aac30d4-132d-4608-b233-d40658ff31b0)

I imagine adding this code might fix the problem:
![image](https://github.com/user-attachments/assets/681e26f5-b2b3-4441-8e52-deacc01d59e5)

2024-11-15 16:31 UTC, joshrsamuel commented on src/pages/webteam.js
Good spot! Just fixed it!

2024-11-15 18:50 UTC, husnajakeer reviewed
All of these changes look great! I am now able to see the favicon display across all pages.

2024-11-15 23:55 UTC, husnajakeer approved these changes
All of the correct page names now display correctly! Thank you for fixing this Josh!

2024-11-16 00:00 UTC, AmaraWilliams approved these changes
Looks good! All pages have a title and favicon now!

2024-11-16 00:01 UTC, merged