Diana navbar
EmpathyBytes/empathy-bytes-2024-2025 pull request #29
Opened 2024-11-25 21:33 UTC by dgarciaperales

Fixed: The "about" and "contact" page, hover functionality, h2 overlapping/conflicting styling, conflicting footer inconsistencies, and font inconsistencies.

2024-11-26 16:34 UTC, AmaraWilliams approved these changes
Great job fixing the functionality and the padding on the header! I'll approve it, however I would appreciate if you added comments and added a more descriptive pull request description that includes a before and after picture. You can follow Josh's PR template or simply take a look at previous PRs that got merged.

2024-11-26 16:34 UTC, AmaraWilliams commented on src/styles/navstyles.css
> +  header {
Could you add a comment for all the styles you have in here? That way it's easier to understand what parts of the site they change without having to go back and forth between the javascript and css files. Same kind of comment you have on line 51 is what I'm looking for.

2024-11-26 21:55 UTC, joshrsamuel requested changes

2024-11-26 21:55 UTC, joshrsamuel commented on src/components/newnav.js
> +            <h2 className="body"> Empathy Bytes</h2>
Pr looks great! Only thing is, I think i'd be great if users could not only click on the logo, but also the name of our VIP to return to the hime page. This should be as easy as wrapping the h2 in a link as well. 

```
<Link to={"/"}>
            <h2 className="body"> Empathy Bytes</h2>
 </Link>
```

2024-12-04 20:01 UTC, joshrsamuel approved these changes
Great work Diana! Thank you for implementing the changes I suggested. The only issue I still see is the scrolling issue we saw on Tiffany and Xavier's tickets, but I think this will be solved with another ticket/issue.

2024-12-04 23:08 UTC, merged